version: '3'
services:
  tpfoyer:
    image: salmasaidi/tpfoyer  # Replace with your actual image
    ports:
      - "8082:8082"  # Map to appropriate ports if necessary
    environment:
      - ENV_VAR=value  # Define any environment variables needed
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tpfoyerdb
    ports:
      - "3306:3306"
